version: "4.1"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    profiles:
      - development
    command: npm run start
    ports:
      - "3434:3434"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
